In [3]:
import torch
import torch.nn.functional as F

In [9]:
predictions = torch.tensor([[0.304, 0.333, 0.363],
                            [0.442, 0.279, 0.279]])
labels = torch.tensor([2, 0])

In [18]:
pred_e = torch.pow(torch.e, predictions)
pred_softmax = pred_e / (pred_e.sum(dim=1, keepdim=True) + torch.finfo(pred_e.dtype).eps)
print(pred_softmax)

tensor([[0.3236, 0.3331, 0.3433],
        [0.3705, 0.3148, 0.3148]])


In [20]:
pred_softmax_2 = predictions.softmax(dim=1)
pred_softmax_2

tensor([[0.3236, 0.3331, 0.3433],
        [0.3705, 0.3148, 0.3148]])

In [8]:
predictions_softmax = F.softmax(predictions,dim=1)
print(predictions)

tensor([[0.3040, 0.3330, 0.3630],
        [0.4420, 0.2790, 0.2790]])
